version: "3.9"
services:
  client: 
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - '3000:5173'
    volumes:
      - ./client:/usr/app
      - /usr/app/build
      - /usr/app/node_modules
  
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./api:/usr/app
      - /usr/app/node_modules
